// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0fRQWWINFkvE-7-eg10X9XMNjdV7k2jg',
    appId: '1:646094031246:web:232ede2712c473e4f17cdf',
    messagingSenderId: '646094031246',
    projectId: 'hairtech-smile',
    authDomain: 'hairtech-smile.firebaseapp.com',
    storageBucket: 'hairtech-smile.firebasestorage.app',
    measurementId: 'G-C7PHGV8YFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuuys1_mQlRHQzMXLZL0lH_7cqC2S8n7M',
    appId: '1:646094031246:android:b6c4e18112294f03f17cdf',
    messagingSenderId: '646094031246',
    projectId: 'hairtech-smile',
    storageBucket: 'hairtech-smile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsj4zr9mHfcDCA-v7nQ9z0SNnVyFp-p_I',
    appId: '1:646094031246:ios:e337662f6aaf7eddf17cdf',
    messagingSenderId: '646094031246',
    projectId: 'hairtech-smile',
    storageBucket: 'hairtech-smile.firebasestorage.app',
    iosBundleId: 'com.example.hairtech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsj4zr9mHfcDCA-v7nQ9z0SNnVyFp-p_I',
    appId: '1:646094031246:ios:e337662f6aaf7eddf17cdf',
    messagingSenderId: '646094031246',
    projectId: 'hairtech-smile',
    storageBucket: 'hairtech-smile.firebasestorage.app',
    iosBundleId: 'com.example.hairtech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0fRQWWINFkvE-7-eg10X9XMNjdV7k2jg',
    appId: '1:646094031246:web:2c2b194397ae5850f17cdf',
    messagingSenderId: '646094031246',
    projectId: 'hairtech-smile',
    authDomain: 'hairtech-smile.firebaseapp.com',
    storageBucket: 'hairtech-smile.firebasestorage.app',
    measurementId: 'G-ST46HYHQZ8',
  );
}
